//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem_Application.Web.API.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailVerification
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public string OTP { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
