//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem_Application.Web.API.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BillNumber { get; set; }
        public string PartyName { get; set; }
        public string Address { get; set; }
        public string GSTNumber { get; set; }
        public string Broker { get; set; }
        public string Brokarage { get; set; }
        public string DescriptionOfGoods { get; set; }
        public string QuantityKg { get; set; }
        public string Rate { get; set; }
        public string APMC { get; set; }
        public string Packing { get; set; }
        public string CGST { get; set; }
        public string SGST { get; set; }
        public string IGST { get; set; }
        public string GrandTotal { get; set; }
        public string BankDetail { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
        public string ChequeAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> UploadType { get; set; }
    }
}
