//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem_Application.Web.API.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheetMaster
    {
        public int Id { get; set; }
        public string SheetName { get; set; }
        public string SheetType { get; set; }
        public string SheetColumnName { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
