//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingSystem_Application.Web.API.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChiragSpicesEntities : DbContext
    {
        public ChiragSpicesEntities()
            : base("name=ChiragSpicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddessDetail> AddessDetails { get; set; }
        public virtual DbSet<ConfigurationMaster> ConfigurationMasters { get; set; }
        public virtual DbSet<EmailVerification> EmailVerifications { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<ProductTypeMaster> ProductTypeMasters { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SheetMaster> SheetMasters { get; set; }
        public virtual DbSet<TaxOnProduct> TaxOnProducts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Verification> Verifications { get; set; }
    }
}
